<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5c84da4ded0e2',
	'title' => 'Post Fields',
	'fields' => array(
		array(
			'key' => 'field_5c84da7cab4c7',
			'label' => 'Ort',
			'name' => 'location',
			'type' => 'text',
			'instructions' => 'Der Suffix "Berlin" oder "Potsdam" wird zum filtern benutzt, sollte also immer gesetzt werden, wenn es sich anbietet.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Musterstadt Straße 5, Potsdam',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c84da86ab4c8',
			'label' => 'Zeit',
			'name' => 'time',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Jeden Sonntag, 14:00 Uhr',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c84dae0ab4c9',
			'label' => 'Nur aktiv bis ...',
			'name' => 'expiry',
			'type' => 'date_picker',
			'instructions' => 'Das letzte Datum, an dem dieser Eintrag noch gezeigt werden soll',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'F j, Y',
			'return_format' => 'Ymd',
			'first_day' => 1,
		),
		array(
			'key' => 'field_5c84da54ab4c5',
			'label' => 'Nur für Frauen',
			'name' => 'women_only',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5c84da67ab4c6',
			'label' => 'Deutschkenntnisse erforderlich',
			'name' => 'german_required',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5c84f00d4b52c',
			'label' => 'Anhang',
			'name' => 'attachment',
			'type' => 'file',
			'instructions' => 'Zum Beispiel ein Flyer oder andere Dateien zum Event',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

endif;
